name: BlessYourBody
favicon: null
layout_spectrum: 0.20120643824338913
typography_spectrum: 0.8277923697605729
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.2500988426618278
  lightness: 0.15374988201074302
  saturation: 0.49887764104641974
  rhythmicContrast: 0.9099026820622385
purpose: []
